# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from timelight_ai_python_api_client.api_client import ApiClient


class AlertApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def v1_alert_alert_id_comment_patch(self, alert_comment_dto, alert_id, **kwargs):  # noqa: E501
        """Add a comment to an alert  # noqa: E501

        A commented alert is closed and is moved to the alert referential  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_alert_alert_id_comment_patch(alert_comment_dto, alert_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param AlertCommentDto alert_comment_dto: (required)
        :param float alert_id: (required)
        :return: AlertRefDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.v1_alert_alert_id_comment_patch_with_http_info(alert_comment_dto, alert_id, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_alert_alert_id_comment_patch_with_http_info(alert_comment_dto, alert_id, **kwargs)  # noqa: E501
            return data

    def v1_alert_alert_id_comment_patch_with_http_info(self, alert_comment_dto, alert_id, **kwargs):  # noqa: E501
        """Add a comment to an alert  # noqa: E501

        A commented alert is closed and is moved to the alert referential  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_alert_alert_id_comment_patch_with_http_info(alert_comment_dto, alert_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param AlertCommentDto alert_comment_dto: (required)
        :param float alert_id: (required)
        :return: AlertRefDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['alert_comment_dto', 'alert_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_alert_alert_id_comment_patch" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'alert_comment_dto' is set
        if ('alert_comment_dto' not in params or
                params['alert_comment_dto'] is None):
            raise ValueError("Missing the required parameter `alert_comment_dto` when calling `v1_alert_alert_id_comment_patch`")  # noqa: E501
        # verify the required parameter 'alert_id' is set
        if ('alert_id' not in params or
                params['alert_id'] is None):
            raise ValueError("Missing the required parameter `alert_id` when calling `v1_alert_alert_id_comment_patch`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'alert_id' in params:
            path_params['alertId'] = params['alert_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'alert_comment_dto' in params:
            body_params = params['alert_comment_dto']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearer']  # noqa: E501

        return self.api_client.call_api(
            '/v1/alert/{alertId}/comment', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AlertRefDto',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_alert_alert_id_favorite_patch(self, alert_favorite_dto, alert_id, **kwargs):  # noqa: E501
        """Set alert favorite for the current user  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_alert_alert_id_favorite_patch(alert_favorite_dto, alert_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param AlertFavoriteDto alert_favorite_dto: (required)
        :param float alert_id: (required)
        :return: AlertDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.v1_alert_alert_id_favorite_patch_with_http_info(alert_favorite_dto, alert_id, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_alert_alert_id_favorite_patch_with_http_info(alert_favorite_dto, alert_id, **kwargs)  # noqa: E501
            return data

    def v1_alert_alert_id_favorite_patch_with_http_info(self, alert_favorite_dto, alert_id, **kwargs):  # noqa: E501
        """Set alert favorite for the current user  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_alert_alert_id_favorite_patch_with_http_info(alert_favorite_dto, alert_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param AlertFavoriteDto alert_favorite_dto: (required)
        :param float alert_id: (required)
        :return: AlertDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['alert_favorite_dto', 'alert_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_alert_alert_id_favorite_patch" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'alert_favorite_dto' is set
        if ('alert_favorite_dto' not in params or
                params['alert_favorite_dto'] is None):
            raise ValueError("Missing the required parameter `alert_favorite_dto` when calling `v1_alert_alert_id_favorite_patch`")  # noqa: E501
        # verify the required parameter 'alert_id' is set
        if ('alert_id' not in params or
                params['alert_id'] is None):
            raise ValueError("Missing the required parameter `alert_id` when calling `v1_alert_alert_id_favorite_patch`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'alert_id' in params:
            path_params['alertId'] = params['alert_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'alert_favorite_dto' in params:
            body_params = params['alert_favorite_dto']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearer']  # noqa: E501

        return self.api_client.call_api(
            '/v1/alert/{alertId}/favorite', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AlertDto',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_alert_list_get(self, **kwargs):  # noqa: E501
        """List alerts data of the selected year, all alerts if no year is provided  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_alert_list_get(async=True)
        >>> result = thread.get()

        :param async bool
        :param float source_id:
        :param float year:
        :return: AlertListDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.v1_alert_list_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.v1_alert_list_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def v1_alert_list_get_with_http_info(self, **kwargs):  # noqa: E501
        """List alerts data of the selected year, all alerts if no year is provided  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_alert_list_get_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param float source_id:
        :param float year:
        :return: AlertListDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['source_id', 'year']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_alert_list_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'source_id' in params:
            query_params.append(('sourceId', params['source_id']))  # noqa: E501
        if 'year' in params:
            query_params.append(('year', params['year']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearer']  # noqa: E501

        return self.api_client.call_api(
            '/v1/alert/list', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AlertListDto',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_alert_ref_list_get(self, **kwargs):  # noqa: E501
        """List alerts data of the selected year, all alerts if no year is provided  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_alert_ref_list_get(async=True)
        >>> result = thread.get()

        :param async bool
        :param float source_id:
        :param float year:
        :return: AlertRefListDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.v1_alert_ref_list_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.v1_alert_ref_list_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def v1_alert_ref_list_get_with_http_info(self, **kwargs):  # noqa: E501
        """List alerts data of the selected year, all alerts if no year is provided  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_alert_ref_list_get_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param float source_id:
        :param float year:
        :return: AlertRefListDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['source_id', 'year']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_alert_ref_list_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'source_id' in params:
            query_params.append(('sourceId', params['source_id']))  # noqa: E501
        if 'year' in params:
            query_params.append(('year', params['year']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearer']  # noqa: E501

        return self.api_client.call_api(
            '/v1/alert/ref/list', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AlertRefListDto',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
