# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight_ai_python_api_client
from timelight_ai_python_api_client.api.onboarding_api import OnboardingApi  # noqa: E501
from timelight_ai_python_api_client.rest import ApiException


class TestOnboardingApi(unittest.TestCase):
    """OnboardingApi unit test stubs"""

    def setUp(self):
        self.api = timelight_ai_python_api_client.api.onboarding_api.OnboardingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_onboarding_analyze_csv_post(self):
        """Test case for v1_onboarding_analyze_csv_post

        Analyze a csv input  # noqa: E501
        """
        pass

    def test_v1_onboarding_validate_csv_post(self):
        """Test case for v1_onboarding_validate_csv_post

        Checks that our onboarding csv file is valid  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
