# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight-ai-python-api-client
from timelight-ai-python-api-client.api.source_group_api import SourceGroupApi  # noqa: E501
from timelight-ai-python-api-client.rest import ApiException


class TestSourceGroupApi(unittest.TestCase):
    """SourceGroupApi unit test stubs"""

    def setUp(self):
        self.api = timelight-ai-python-api-client.api.source_group_api.SourceGroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_source_group_create_post(self):
        """Test case for v1_source_group_create_post

        Create a new source groups  # noqa: E501
        """
        pass

    def test_v1_source_group_group_id_patch(self):
        """Test case for v1_source_group_group_id_patch

        Updates a group configuration  # noqa: E501
        """
        pass

    def test_v1_source_group_list_get(self):
        """Test case for v1_source_group_list_get

        All source groups  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
