# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight-ai-python-api-client
from timelight-ai-python-api-client.api.model_api import ModelApi  # noqa: E501
from timelight-ai-python-api-client.rest import ApiException


class TestModelApi(unittest.TestCase):
    """ModelApi unit test stubs"""

    def setUp(self):
        self.api = timelight-ai-python-api-client.api.model_api.ModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_model_bulk_patch(self):
        """Test case for v1_model_bulk_patch

        Model bulk update  # noqa: E501
        """
        pass

    def test_v1_model_list_source_id_get(self):
        """Test case for v1_model_list_source_id_get

        List models data of this source  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
