# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight-ai-python-api-client
from timelight-ai-python-api-client.models.recompute_source_models_response_dto import RecomputeSourceModelsResponseDto  # noqa: E501
from timelight-ai-python-api-client.rest import ApiException


class TestRecomputeSourceModelsResponseDto(unittest.TestCase):
    """RecomputeSourceModelsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecomputeSourceModelsResponseDto(self):
        """Test RecomputeSourceModelsResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = timelight-ai-python-api-client.models.recompute_source_models_response_dto.RecomputeSourceModelsResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
