# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight-ai-python-api-client
from timelight-ai-python-api-client.api.ai_api import AIApi  # noqa: E501
from timelight-ai-python-api-client.rest import ApiException


class TestAIApi(unittest.TestCase):
    """AIApi unit test stubs"""

    def setUp(self):
        self.api = timelight-ai-python-api-client.api.ai_api.AIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_ai_anomalies_source_id_get(self):
        """Test case for v1_ai_anomalies_source_id_get

        Auto detect-anomalies  # noqa: E501
        """
        pass

    def test_v1_ai_recompute_day_models_source_id_year_post(self):
        """Test case for v1_ai_recompute_day_models_source_id_year_post

        Recomputes all day modesl  # noqa: E501
        """
        pass

    def test_v1_ai_recompute_days_projection_source_id_year_post(self):
        """Test case for v1_ai_recompute_days_projection_source_id_year_post

        Computes all days projection for a source and save them  # noqa: E501
        """
        pass

    def test_v1_ai_recompute_models_source_id_year_post(self):
        """Test case for v1_ai_recompute_models_source_id_year_post

        Triggers a model recompute  # noqa: E501
        """
        pass

    def test_v1_ai_recompute_source_models_model_count_post(self):
        """Test case for v1_ai_recompute_source_models_model_count_post

        Triggers a model recompute for source groups  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
