# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight_ai_python_api_client
from timelight_ai_python_api_client.models.model_post_dto import ModelPostDto  # noqa: E501
from timelight_ai_python_api_client.rest import ApiException


class TestModelPostDto(unittest.TestCase):
    """ModelPostDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelPostDto(self):
        """Test ModelPostDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = timelight_ai_python_api_client.models.model_post_dto.ModelPostDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
