# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight_ai_python_api_client
from timelight_ai_python_api_client.api.view_helper_api import ViewHelperApi  # noqa: E501
from timelight_ai_python_api_client.rest import ApiException


class TestViewHelperApi(unittest.TestCase):
    """ViewHelperApi unit test stubs"""

    def setUp(self):
        self.api = timelight_ai_python_api_client.api.view_helper_api.ViewHelperApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_view_helper_alerts_get(self):
        """Test case for v1_view_helper_alerts_get

        Get the alert view data  # noqa: E501
        """
        pass

    def test_v1_view_helper_alerts_ref_get(self):
        """Test case for v1_view_helper_alerts_ref_get

        Get the alert referential view data  # noqa: E501
        """
        pass

    def test_v1_view_helper_days_near_date_source_id_day_date_get(self):
        """Test case for v1_view_helper_days_near_date_source_id_day_date_get

        Get the alert modal view data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
