# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight_ai_python_api_client
from timelight_ai_python_api_client.models.alert_list_dto import AlertListDto  # noqa: E501
from timelight_ai_python_api_client.rest import ApiException


class TestAlertListDto(unittest.TestCase):
    """AlertListDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertListDto(self):
        """Test AlertListDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = timelight_ai_python_api_client.models.alert_list_dto.AlertListDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
