# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight-ai-python-api-client
from timelight-ai-python-api-client.api.prevision_api import PrevisionApi  # noqa: E501
from timelight-ai-python-api-client.rest import ApiException


class TestPrevisionApi(unittest.TestCase):
    """PrevisionApi unit test stubs"""

    def setUp(self):
        self.api = timelight-ai-python-api-client.api.prevision_api.PrevisionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_prevision_group_apply_prevision_post(self):
        """Test case for v1_prevision_group_apply_prevision_post

        Apply a source prevision to the whole group  # noqa: E501
        """
        pass

    def test_v1_prevision_list_source_id_year_get(self):
        """Test case for v1_prevision_list_source_id_year_get

        Fetch data previsions for a given year  # noqa: E501
        """
        pass

    def test_v1_prevision_save_default_previsions_source_id_year_post(self):
        """Test case for v1_prevision_save_default_previsions_source_id_year_post

        Generate default previsions for the source and save them  # noqa: E501
        """
        pass

    def test_v1_prevision_save_post(self):
        """Test case for v1_prevision_save_post

        Save many previsions at once  # noqa: E501
        """
        pass

    def test_v1_prevision_update_patch(self):
        """Test case for v1_prevision_update_patch

        Update a specific prevision  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
