# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight-ai-python-api-client
from timelight-ai-python-api-client.api.alert_api import AlertApi  # noqa: E501
from timelight-ai-python-api-client.rest import ApiException


class TestAlertApi(unittest.TestCase):
    """AlertApi unit test stubs"""

    def setUp(self):
        self.api = timelight-ai-python-api-client.api.alert_api.AlertApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_alert_alert_id_comment_patch(self):
        """Test case for v1_alert_alert_id_comment_patch

        Add a comment to an alert  # noqa: E501
        """
        pass

    def test_v1_alert_alert_id_favorite_patch(self):
        """Test case for v1_alert_alert_id_favorite_patch

        Set alert favorite for the current user  # noqa: E501
        """
        pass

    def test_v1_alert_list_get(self):
        """Test case for v1_alert_list_get

        List alerts data of the selected year, all alerts if no year is provided  # noqa: E501
        """
        pass

    def test_v1_alert_ref_list_get(self):
        """Test case for v1_alert_ref_list_get

        List alerts data of the selected year, all alerts if no year is provided  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
