# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight-ai-python-api-client
from timelight-ai-python-api-client.api.import_api import ImportApi  # noqa: E501
from timelight-ai-python-api-client.rest import ApiException


class TestImportApi(unittest.TestCase):
    """ImportApi unit test stubs"""

    def setUp(self):
        self.api = timelight-ai-python-api-client.api.import_api.ImportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_import_create_source_post(self):
        """Test case for v1_import_create_source_post

        First source creation  # noqa: E501
        """
        pass

    def test_v1_import_days_post(self):
        """Test case for v1_import_days_post

        Add new data to a source  # noqa: E501
        """
        pass

    def test_v1_import_reprocess_days_source_id_year_post(self):
        """Test case for v1_import_reprocess_days_source_id_year_post

        Reprocess days from database  # noqa: E501
        """
        pass

    def test_v1_import_source_id_days_post(self):
        """Test case for v1_import_source_id_days_post

        Add new data to a source  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
