# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight-ai-python-api-client
from timelight-ai-python-api-client.models.recompute_models_response_dto import RecomputeModelsResponseDto  # noqa: E501
from timelight-ai-python-api-client.rest import ApiException


class TestRecomputeModelsResponseDto(unittest.TestCase):
    """RecomputeModelsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecomputeModelsResponseDto(self):
        """Test RecomputeModelsResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = timelight-ai-python-api-client.models.recompute_models_response_dto.RecomputeModelsResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
