# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import timelight-ai-python-api-client
from timelight-ai-python-api-client.api.source_api import SourceApi  # noqa: E501
from timelight-ai-python-api-client.rest import ApiException


class TestSourceApi(unittest.TestCase):
    """SourceApi unit test stubs"""

    def setUp(self):
        self.api = timelight-ai-python-api-client.api.source_api.SourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_source_list_get(self):
        """Test case for v1_source_list_get

        All user sources  # noqa: E501
        """
        pass

    def test_v1_source_source_id_delete(self):
        """Test case for v1_source_source_id_delete

        Delete a source and all linked data  # noqa: E501
        """
        pass

    def test_v1_source_source_id_group_patch(self):
        """Test case for v1_source_source_id_group_patch

        Update a source group  # noqa: E501
        """
        pass

    def test_v1_source_source_id_patch(self):
        """Test case for v1_source_source_id_patch

        Update a source  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
