# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from timelight_ai_python_api_client.models.day_trend import DayTrend  # noqa: F401,E501


class GeneratedDayTrendBulkDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bulk': 'list[DayTrend]'
    }

    attribute_map = {
        'bulk': 'bulk'
    }

    def __init__(self, bulk=None):  # noqa: E501
        """GeneratedDayTrendBulkDto - a model defined in Swagger"""  # noqa: E501

        self._bulk = None
        self.discriminator = None

        self.bulk = bulk

    @property
    def bulk(self):
        """Gets the bulk of this GeneratedDayTrendBulkDto.  # noqa: E501


        :return: The bulk of this GeneratedDayTrendBulkDto.  # noqa: E501
        :rtype: list[DayTrend]
        """
        return self._bulk

    @bulk.setter
    def bulk(self, bulk):
        """Sets the bulk of this GeneratedDayTrendBulkDto.


        :param bulk: The bulk of this GeneratedDayTrendBulkDto.  # noqa: E501
        :type: list[DayTrend]
        """
        if bulk is None:
            raise ValueError("Invalid value for `bulk`, must not be `None`")  # noqa: E501

        self._bulk = bulk

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeneratedDayTrendBulkDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
