# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ModelPostDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'color': 'str',
        'name': 'str',
        'anomaly': 'bool',
        'top_tolerance': 'list[float]',
        'activity': 'list[float]',
        'bottom_tolerance': 'list[float]'
    }

    attribute_map = {
        'color': 'color',
        'name': 'name',
        'anomaly': 'anomaly',
        'top_tolerance': 'topTolerance',
        'activity': 'activity',
        'bottom_tolerance': 'bottomTolerance'
    }

    def __init__(self, color=None, name=None, anomaly=None, top_tolerance=None, activity=None, bottom_tolerance=None):  # noqa: E501
        """ModelPostDto - a model defined in Swagger"""  # noqa: E501

        self._color = None
        self._name = None
        self._anomaly = None
        self._top_tolerance = None
        self._activity = None
        self._bottom_tolerance = None
        self.discriminator = None

        self.color = color
        self.name = name
        self.anomaly = anomaly
        self.top_tolerance = top_tolerance
        self.activity = activity
        self.bottom_tolerance = bottom_tolerance

    @property
    def color(self):
        """Gets the color of this ModelPostDto.  # noqa: E501

        The color in hex format. Ex: '#FFFFFF'  # noqa: E501

        :return: The color of this ModelPostDto.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this ModelPostDto.

        The color in hex format. Ex: '#FFFFFF'  # noqa: E501

        :param color: The color of this ModelPostDto.  # noqa: E501
        :type: str
        """
        if color is None:
            raise ValueError("Invalid value for `color`, must not be `None`")  # noqa: E501

        self._color = color

    @property
    def name(self):
        """Gets the name of this ModelPostDto.  # noqa: E501

        The model name, between 1 and 100 characters  # noqa: E501

        :return: The name of this ModelPostDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ModelPostDto.

        The model name, between 1 and 100 characters  # noqa: E501

        :param name: The name of this ModelPostDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def anomaly(self):
        """Gets the anomaly of this ModelPostDto.  # noqa: E501

        True if the model is an anomaly and should be ignored by the ML engine  # noqa: E501

        :return: The anomaly of this ModelPostDto.  # noqa: E501
        :rtype: bool
        """
        return self._anomaly

    @anomaly.setter
    def anomaly(self, anomaly):
        """Sets the anomaly of this ModelPostDto.

        True if the model is an anomaly and should be ignored by the ML engine  # noqa: E501

        :param anomaly: The anomaly of this ModelPostDto.  # noqa: E501
        :type: bool
        """
        if anomaly is None:
            raise ValueError("Invalid value for `anomaly`, must not be `None`")  # noqa: E501

        self._anomaly = anomaly

    @property
    def top_tolerance(self):
        """Gets the top_tolerance of this ModelPostDto.  # noqa: E501

        An array of 144, 1440 or 86400 values. Each value represents a time window of 10 minutes, 1 minute or 1 second  # noqa: E501

        :return: The top_tolerance of this ModelPostDto.  # noqa: E501
        :rtype: list[float]
        """
        return self._top_tolerance

    @top_tolerance.setter
    def top_tolerance(self, top_tolerance):
        """Sets the top_tolerance of this ModelPostDto.

        An array of 144, 1440 or 86400 values. Each value represents a time window of 10 minutes, 1 minute or 1 second  # noqa: E501

        :param top_tolerance: The top_tolerance of this ModelPostDto.  # noqa: E501
        :type: list[float]
        """
        if top_tolerance is None:
            raise ValueError("Invalid value for `top_tolerance`, must not be `None`")  # noqa: E501

        self._top_tolerance = top_tolerance

    @property
    def activity(self):
        """Gets the activity of this ModelPostDto.  # noqa: E501

        An array of 144, 1440 or 86400 values. Each value represents a time window of 10 minutes, 1 minute or 1 second  # noqa: E501

        :return: The activity of this ModelPostDto.  # noqa: E501
        :rtype: list[float]
        """
        return self._activity

    @activity.setter
    def activity(self, activity):
        """Sets the activity of this ModelPostDto.

        An array of 144, 1440 or 86400 values. Each value represents a time window of 10 minutes, 1 minute or 1 second  # noqa: E501

        :param activity: The activity of this ModelPostDto.  # noqa: E501
        :type: list[float]
        """
        if activity is None:
            raise ValueError("Invalid value for `activity`, must not be `None`")  # noqa: E501

        self._activity = activity

    @property
    def bottom_tolerance(self):
        """Gets the bottom_tolerance of this ModelPostDto.  # noqa: E501

        An array of 144, 1440 or 86400 values. Each value represents a time window of 10 minutes, 1 minute or 1 second  # noqa: E501

        :return: The bottom_tolerance of this ModelPostDto.  # noqa: E501
        :rtype: list[float]
        """
        return self._bottom_tolerance

    @bottom_tolerance.setter
    def bottom_tolerance(self, bottom_tolerance):
        """Sets the bottom_tolerance of this ModelPostDto.

        An array of 144, 1440 or 86400 values. Each value represents a time window of 10 minutes, 1 minute or 1 second  # noqa: E501

        :param bottom_tolerance: The bottom_tolerance of this ModelPostDto.  # noqa: E501
        :type: list[float]
        """
        if bottom_tolerance is None:
            raise ValueError("Invalid value for `bottom_tolerance`, must not be `None`")  # noqa: E501

        self._bottom_tolerance = bottom_tolerance

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelPostDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelPostDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
