# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ModelDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'float',
        'color': 'str',
        'name': 'str',
        'activity': 'list[float]',
        'top_tolerance': 'list[float]',
        'bottom_tolerance': 'list[float]',
        'x': 'float',
        'y': 'float',
        'value': 'float',
        'anomaly': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'color': 'color',
        'name': 'name',
        'activity': 'activity',
        'top_tolerance': 'top_tolerance',
        'bottom_tolerance': 'bottom_tolerance',
        'x': 'x',
        'y': 'y',
        'value': 'value',
        'anomaly': 'anomaly'
    }

    def __init__(self, id=None, color=None, name=None, activity=None, top_tolerance=None, bottom_tolerance=None, x=None, y=None, value=None, anomaly=None):  # noqa: E501
        """ModelDto - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._color = None
        self._name = None
        self._activity = None
        self._top_tolerance = None
        self._bottom_tolerance = None
        self._x = None
        self._y = None
        self._value = None
        self._anomaly = None
        self.discriminator = None

        self.id = id
        self.color = color
        self.name = name
        self.activity = activity
        self.top_tolerance = top_tolerance
        self.bottom_tolerance = bottom_tolerance
        self.x = x
        self.y = y
        self.value = value
        self.anomaly = anomaly

    @property
    def id(self):
        """Gets the id of this ModelDto.  # noqa: E501


        :return: The id of this ModelDto.  # noqa: E501
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ModelDto.


        :param id: The id of this ModelDto.  # noqa: E501
        :type: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def color(self):
        """Gets the color of this ModelDto.  # noqa: E501


        :return: The color of this ModelDto.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this ModelDto.


        :param color: The color of this ModelDto.  # noqa: E501
        :type: str
        """
        if color is None:
            raise ValueError("Invalid value for `color`, must not be `None`")  # noqa: E501

        self._color = color

    @property
    def name(self):
        """Gets the name of this ModelDto.  # noqa: E501


        :return: The name of this ModelDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ModelDto.


        :param name: The name of this ModelDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def activity(self):
        """Gets the activity of this ModelDto.  # noqa: E501


        :return: The activity of this ModelDto.  # noqa: E501
        :rtype: list[float]
        """
        return self._activity

    @activity.setter
    def activity(self, activity):
        """Sets the activity of this ModelDto.


        :param activity: The activity of this ModelDto.  # noqa: E501
        :type: list[float]
        """
        if activity is None:
            raise ValueError("Invalid value for `activity`, must not be `None`")  # noqa: E501

        self._activity = activity

    @property
    def top_tolerance(self):
        """Gets the top_tolerance of this ModelDto.  # noqa: E501


        :return: The top_tolerance of this ModelDto.  # noqa: E501
        :rtype: list[float]
        """
        return self._top_tolerance

    @top_tolerance.setter
    def top_tolerance(self, top_tolerance):
        """Sets the top_tolerance of this ModelDto.


        :param top_tolerance: The top_tolerance of this ModelDto.  # noqa: E501
        :type: list[float]
        """
        if top_tolerance is None:
            raise ValueError("Invalid value for `top_tolerance`, must not be `None`")  # noqa: E501

        self._top_tolerance = top_tolerance

    @property
    def bottom_tolerance(self):
        """Gets the bottom_tolerance of this ModelDto.  # noqa: E501


        :return: The bottom_tolerance of this ModelDto.  # noqa: E501
        :rtype: list[float]
        """
        return self._bottom_tolerance

    @bottom_tolerance.setter
    def bottom_tolerance(self, bottom_tolerance):
        """Sets the bottom_tolerance of this ModelDto.


        :param bottom_tolerance: The bottom_tolerance of this ModelDto.  # noqa: E501
        :type: list[float]
        """
        if bottom_tolerance is None:
            raise ValueError("Invalid value for `bottom_tolerance`, must not be `None`")  # noqa: E501

        self._bottom_tolerance = bottom_tolerance

    @property
    def x(self):
        """Gets the x of this ModelDto.  # noqa: E501


        :return: The x of this ModelDto.  # noqa: E501
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this ModelDto.


        :param x: The x of this ModelDto.  # noqa: E501
        :type: float
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self):
        """Gets the y of this ModelDto.  # noqa: E501


        :return: The y of this ModelDto.  # noqa: E501
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this ModelDto.


        :param y: The y of this ModelDto.  # noqa: E501
        :type: float
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y

    @property
    def value(self):
        """Gets the value of this ModelDto.  # noqa: E501


        :return: The value of this ModelDto.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ModelDto.


        :param value: The value of this ModelDto.  # noqa: E501
        :type: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def anomaly(self):
        """Gets the anomaly of this ModelDto.  # noqa: E501


        :return: The anomaly of this ModelDto.  # noqa: E501
        :rtype: bool
        """
        return self._anomaly

    @anomaly.setter
    def anomaly(self, anomaly):
        """Sets the anomaly of this ModelDto.


        :param anomaly: The anomaly of this ModelDto.  # noqa: E501
        :type: bool
        """
        if anomaly is None:
            raise ValueError("Invalid value for `anomaly`, must not be `None`")  # noqa: E501

        self._anomaly = anomaly

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
