# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ModelPatchDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'float',
        'color': 'str',
        'name': 'str',
        'anomaly': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'color': 'color',
        'name': 'name',
        'anomaly': 'anomaly'
    }

    def __init__(self, id=None, color=None, name=None, anomaly=None):  # noqa: E501
        """ModelPatchDto - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._color = None
        self._name = None
        self._anomaly = None
        self.discriminator = None

        self.id = id
        self.color = color
        self.name = name
        self.anomaly = anomaly

    @property
    def id(self):
        """Gets the id of this ModelPatchDto.  # noqa: E501

        The model id  # noqa: E501

        :return: The id of this ModelPatchDto.  # noqa: E501
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ModelPatchDto.

        The model id  # noqa: E501

        :param id: The id of this ModelPatchDto.  # noqa: E501
        :type: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def color(self):
        """Gets the color of this ModelPatchDto.  # noqa: E501

        The color in hex format. Ex: '#FFFFFF'  # noqa: E501

        :return: The color of this ModelPatchDto.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this ModelPatchDto.

        The color in hex format. Ex: '#FFFFFF'  # noqa: E501

        :param color: The color of this ModelPatchDto.  # noqa: E501
        :type: str
        """
        if color is None:
            raise ValueError("Invalid value for `color`, must not be `None`")  # noqa: E501

        self._color = color

    @property
    def name(self):
        """Gets the name of this ModelPatchDto.  # noqa: E501

        The model name, between 1 and 100 characters  # noqa: E501

        :return: The name of this ModelPatchDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ModelPatchDto.

        The model name, between 1 and 100 characters  # noqa: E501

        :param name: The name of this ModelPatchDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def anomaly(self):
        """Gets the anomaly of this ModelPatchDto.  # noqa: E501

        True if the model is an anomaly and should be ignored by the ML engine  # noqa: E501

        :return: The anomaly of this ModelPatchDto.  # noqa: E501
        :rtype: bool
        """
        return self._anomaly

    @anomaly.setter
    def anomaly(self, anomaly):
        """Sets the anomaly of this ModelPatchDto.

        True if the model is an anomaly and should be ignored by the ML engine  # noqa: E501

        :param anomaly: The anomaly of this ModelPatchDto.  # noqa: E501
        :type: bool
        """
        if anomaly is None:
            raise ValueError("Invalid value for `anomaly`, must not be `None`")  # noqa: E501

        self._anomaly = anomaly

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelPatchDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelPatchDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
