# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RequestDemoDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'str',
        'name': 'str',
        'company': 'str',
        'position': 'str'
    }

    attribute_map = {
        'email': 'email',
        'name': 'name',
        'company': 'company',
        'position': 'position'
    }

    def __init__(self, email=None, name=None, company=None, position=None):  # noqa: E501
        """RequestDemoDto - a model defined in Swagger"""  # noqa: E501

        self._email = None
        self._name = None
        self._company = None
        self._position = None
        self.discriminator = None

        self.email = email
        self.name = name
        self.company = company
        self.position = position

    @property
    def email(self):
        """Gets the email of this RequestDemoDto.  # noqa: E501

        User email  # noqa: E501

        :return: The email of this RequestDemoDto.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this RequestDemoDto.

        User email  # noqa: E501

        :param email: The email of this RequestDemoDto.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def name(self):
        """Gets the name of this RequestDemoDto.  # noqa: E501

        User name  # noqa: E501

        :return: The name of this RequestDemoDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RequestDemoDto.

        User name  # noqa: E501

        :param name: The name of this RequestDemoDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def company(self):
        """Gets the company of this RequestDemoDto.  # noqa: E501

        Company name  # noqa: E501

        :return: The company of this RequestDemoDto.  # noqa: E501
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this RequestDemoDto.

        Company name  # noqa: E501

        :param company: The company of this RequestDemoDto.  # noqa: E501
        :type: str
        """
        if company is None:
            raise ValueError("Invalid value for `company`, must not be `None`")  # noqa: E501

        self._company = company

    @property
    def position(self):
        """Gets the position of this RequestDemoDto.  # noqa: E501

        Company position  # noqa: E501

        :return: The position of this RequestDemoDto.  # noqa: E501
        :rtype: str
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this RequestDemoDto.

        Company position  # noqa: E501

        :param position: The position of this RequestDemoDto.  # noqa: E501
        :type: str
        """
        if position is None:
            raise ValueError("Invalid value for `position`, must not be `None`")  # noqa: E501

        self._position = position

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestDemoDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestDemoDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
