# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SourcePatchDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'prevision_enabled': 'bool',
        'latitude': 'float',
        'longitude': 'float',
        'address': 'str',
        'alert_min_criticity': 'float',
        'alert_max_criticity': 'float'
    }

    attribute_map = {
        'name': 'name',
        'prevision_enabled': 'previsionEnabled',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'address': 'address',
        'alert_min_criticity': 'alertMinCriticity',
        'alert_max_criticity': 'alertMaxCriticity'
    }

    def __init__(self, name=None, prevision_enabled=None, latitude=None, longitude=None, address=None, alert_min_criticity=None, alert_max_criticity=None):  # noqa: E501
        """SourcePatchDto - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._prevision_enabled = None
        self._latitude = None
        self._longitude = None
        self._address = None
        self._alert_min_criticity = None
        self._alert_max_criticity = None
        self.discriminator = None

        self.name = name
        self.prevision_enabled = prevision_enabled
        self.latitude = latitude
        self.longitude = longitude
        self.address = address
        self.alert_min_criticity = alert_min_criticity
        self.alert_max_criticity = alert_max_criticity

    @property
    def name(self):
        """Gets the name of this SourcePatchDto.  # noqa: E501

        The source name  # noqa: E501

        :return: The name of this SourcePatchDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SourcePatchDto.

        The source name  # noqa: E501

        :param name: The name of this SourcePatchDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def prevision_enabled(self):
        """Gets the prevision_enabled of this SourcePatchDto.  # noqa: E501

        The source ability to generate alerts from previsions  # noqa: E501

        :return: The prevision_enabled of this SourcePatchDto.  # noqa: E501
        :rtype: bool
        """
        return self._prevision_enabled

    @prevision_enabled.setter
    def prevision_enabled(self, prevision_enabled):
        """Sets the prevision_enabled of this SourcePatchDto.

        The source ability to generate alerts from previsions  # noqa: E501

        :param prevision_enabled: The prevision_enabled of this SourcePatchDto.  # noqa: E501
        :type: bool
        """
        if prevision_enabled is None:
            raise ValueError("Invalid value for `prevision_enabled`, must not be `None`")  # noqa: E501

        self._prevision_enabled = prevision_enabled

    @property
    def latitude(self):
        """Gets the latitude of this SourcePatchDto.  # noqa: E501

        The source latitude  # noqa: E501

        :return: The latitude of this SourcePatchDto.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this SourcePatchDto.

        The source latitude  # noqa: E501

        :param latitude: The latitude of this SourcePatchDto.  # noqa: E501
        :type: float
        """
        if latitude is None:
            raise ValueError("Invalid value for `latitude`, must not be `None`")  # noqa: E501

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this SourcePatchDto.  # noqa: E501

        The source longitude  # noqa: E501

        :return: The longitude of this SourcePatchDto.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this SourcePatchDto.

        The source longitude  # noqa: E501

        :param longitude: The longitude of this SourcePatchDto.  # noqa: E501
        :type: float
        """
        if longitude is None:
            raise ValueError("Invalid value for `longitude`, must not be `None`")  # noqa: E501

        self._longitude = longitude

    @property
    def address(self):
        """Gets the address of this SourcePatchDto.  # noqa: E501

        The source physical address  # noqa: E501

        :return: The address of this SourcePatchDto.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this SourcePatchDto.

        The source physical address  # noqa: E501

        :param address: The address of this SourcePatchDto.  # noqa: E501
        :type: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def alert_min_criticity(self):
        """Gets the alert_min_criticity of this SourcePatchDto.  # noqa: E501

        The source minimum criticity to trigger an alert  # noqa: E501

        :return: The alert_min_criticity of this SourcePatchDto.  # noqa: E501
        :rtype: float
        """
        return self._alert_min_criticity

    @alert_min_criticity.setter
    def alert_min_criticity(self, alert_min_criticity):
        """Sets the alert_min_criticity of this SourcePatchDto.

        The source minimum criticity to trigger an alert  # noqa: E501

        :param alert_min_criticity: The alert_min_criticity of this SourcePatchDto.  # noqa: E501
        :type: float
        """
        if alert_min_criticity is None:
            raise ValueError("Invalid value for `alert_min_criticity`, must not be `None`")  # noqa: E501

        self._alert_min_criticity = alert_min_criticity

    @property
    def alert_max_criticity(self):
        """Gets the alert_max_criticity of this SourcePatchDto.  # noqa: E501

        The source maximum criticity to trigger an alert  # noqa: E501

        :return: The alert_max_criticity of this SourcePatchDto.  # noqa: E501
        :rtype: float
        """
        return self._alert_max_criticity

    @alert_max_criticity.setter
    def alert_max_criticity(self, alert_max_criticity):
        """Sets the alert_max_criticity of this SourcePatchDto.

        The source maximum criticity to trigger an alert  # noqa: E501

        :param alert_max_criticity: The alert_max_criticity of this SourcePatchDto.  # noqa: E501
        :type: float
        """
        if alert_max_criticity is None:
            raise ValueError("Invalid value for `alert_max_criticity`, must not be `None`")  # noqa: E501

        self._alert_max_criticity = alert_max_criticity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SourcePatchDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SourcePatchDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
