# coding: utf-8

"""
    timelight

    This is the timelight api.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from timelight-ai-python-api-client.api_client import ApiClient


class SourceGroupApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def v1_source_group_create_post(self, source_group_create_dto, **kwargs):  # noqa: E501
        """Create a new source groups  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_source_group_create_post(source_group_create_dto, async=True)
        >>> result = thread.get()

        :param async bool
        :param SourceGroupCreateDto source_group_create_dto: (required)
        :return: SourceGroupDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.v1_source_group_create_post_with_http_info(source_group_create_dto, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_source_group_create_post_with_http_info(source_group_create_dto, **kwargs)  # noqa: E501
            return data

    def v1_source_group_create_post_with_http_info(self, source_group_create_dto, **kwargs):  # noqa: E501
        """Create a new source groups  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_source_group_create_post_with_http_info(source_group_create_dto, async=True)
        >>> result = thread.get()

        :param async bool
        :param SourceGroupCreateDto source_group_create_dto: (required)
        :return: SourceGroupDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['source_group_create_dto']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_source_group_create_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'source_group_create_dto' is set
        if ('source_group_create_dto' not in params or
                params['source_group_create_dto'] is None):
            raise ValueError("Missing the required parameter `source_group_create_dto` when calling `v1_source_group_create_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'source_group_create_dto' in params:
            body_params = params['source_group_create_dto']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearer']  # noqa: E501

        return self.api_client.call_api(
            '/v1/source-group/create', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SourceGroupDto',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_source_group_group_id_patch(self, source_group_patch_dto, group_id, **kwargs):  # noqa: E501
        """Updates a group configuration  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_source_group_group_id_patch(source_group_patch_dto, group_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param SourceGroupPatchDto source_group_patch_dto: (required)
        :param float group_id: (required)
        :return: SourceGroupDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.v1_source_group_group_id_patch_with_http_info(source_group_patch_dto, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.v1_source_group_group_id_patch_with_http_info(source_group_patch_dto, group_id, **kwargs)  # noqa: E501
            return data

    def v1_source_group_group_id_patch_with_http_info(self, source_group_patch_dto, group_id, **kwargs):  # noqa: E501
        """Updates a group configuration  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_source_group_group_id_patch_with_http_info(source_group_patch_dto, group_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param SourceGroupPatchDto source_group_patch_dto: (required)
        :param float group_id: (required)
        :return: SourceGroupDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['source_group_patch_dto', 'group_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_source_group_group_id_patch" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'source_group_patch_dto' is set
        if ('source_group_patch_dto' not in params or
                params['source_group_patch_dto'] is None):
            raise ValueError("Missing the required parameter `source_group_patch_dto` when calling `v1_source_group_group_id_patch`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `v1_source_group_group_id_patch`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'group_id' in params:
            path_params['groupId'] = params['group_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'source_group_patch_dto' in params:
            body_params = params['source_group_patch_dto']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearer']  # noqa: E501

        return self.api_client.call_api(
            '/v1/source-group/{groupId}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SourceGroupDto',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def v1_source_group_list_get(self, **kwargs):  # noqa: E501
        """All source groups  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_source_group_list_get(async=True)
        >>> result = thread.get()

        :param async bool
        :return: SourceGroupListDto
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.v1_source_group_list_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.v1_source_group_list_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def v1_source_group_list_get_with_http_info(self, **kwargs):  # noqa: E501
        """All source groups  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.v1_source_group_list_get_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :return: SourceGroupListDto
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_source_group_list_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearer']  # noqa: E501

        return self.api_client.call_api(
            '/v1/source-group/list', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SourceGroupListDto',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
